services:
  caddy:
    image: caddy:latest
    container_name: caddy
    env_file:
      - path: ../.env
    ports:
      - "${CADDY_HTTP_PORT}:80"
      - "${CADDY_HTTPS_PORT}:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy_data:/data
      - ./caddy_config:/config
      - ../sites:${PROJECTS_PATH}
    environment:
      # Domaines
      DOMAIN: ${DOMAIN}

      # Sous-domaines
      SUBDOMAIN_PHPMYADMIN: ${SUBDOMAIN_PHPMYADMIN}
      SUBDOMAIN_LARAVEL: ${SUBDOMAIN_LARAVEL}
      SUBDOMAIN_SYMFONY: ${SUBDOMAIN_SYMFONY}
      SUBDOMAIN_WORDPRESS: ${SUBDOMAIN_WORDPRESS}
      SUBDOMAIN_PHP: ${SUBDOMAIN_PHP}
      SUBDOMAIN_HTML: ${SUBDOMAIN_HTML}
      SUBDOMAIN_LANDING: ${SUBDOMAIN_LANDING}
      SUBDOMAIN_GO: ${SUBDOMAIN_GO}
      SUBDOMAIN_DJANGO: ${SUBDOMAIN_DJANGO}

      # Chemins des applications
      PROJECTS_PATH: ${PROJECTS_PATH}
      LARAVEL_ROOT: ${LARAVEL_ROOT}
      SYMFONY_ROOT: ${SYMFONY_ROOT}
      WORDPRESS_ROOT: ${WORDPRESS_ROOT}
      PHP_SIMPLE_ROOT: ${PHP_SIMPLE_ROOT}
      HTML_ROOT: ${HTML_ROOT}
      LANDING_ROOT: ${LANDING_ROOT}

      # Ports internes
      PHP_INTERNAL_PORT: ${PHP_INTERNAL_PORT}
      PHPMYADMIN_INTERNAL_PORT: ${PHPMYADMIN_INTERNAL_PORT}
      GO_INTERNAL_PORT: ${GO_INTERNAL_PORT}
      DJANGO_INTERNAL_PORT: ${DJANGO_INTERNAL_PORT}
    networks:
      - app_network
    restart: unless-stopped

  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    restart: unless-stopped
    depends_on:
      - redis
    volumes:
      # Montage en lecture seule pour la sécurité
      - ./authelia/config:/config
    environment:
      # Secrets (gérés par des fichiers dans ./authelia/config/secrets)
      AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE: /config/secrets/JWT_SECRET
      AUTHELIA_SESSION_SECRET_FILE: /config/secrets/SESSION_SECRET
      AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE: /config/secrets/SMTP_PASSWORD
      AUTHELIA_SESSION_REDIS_PASSWORD_FILE: /config/secrets/REDIS_PASSWORD

      # Configuration du stockage (MariaDB/MySQL)
      #AUTHELIA_STORAGE_MYSQL_PASSWORD_FILE: /config/secrets/STORAGE_PASSWORD
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: /config/secrets/STORAGE_ENCRYPTION_KEY
    networks: # Doit être dans le même réseau que Caddy et Redis
      - app_network
      - db_network # Si votre base de données est sur un réseau séparé

  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    command: "redis-server --save 60 1 --loglevel warning --requirepass BtMduRfhPF20VRJ4kFWddPOMkZgTzceffSCEbYSpdjgdUQWMeSaXmZMASuUXfM50"
    volumes:
      - ./redis:/data
    networks:
      - app_network

networks:
  app_network:
    external: true
  db_network:
    external: true
